#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/yli1/ELEN153/lab4/synopsys_custom/pvjob_lab4.NAND.icv.drc/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/yli1/ELEN153/lab4/synopsys_custom/pvjob_lab4.NAND.icv.drc/NAND.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/yli1/ELEN153/lab4/synopsys_custom/pvjob_lab4.NAND.icv.drc/run_details/duse_master.tmp && \
mv /DCNFS/users/student/yli1/ELEN153/lab4/synopsys_custom/pvjob_lab4.NAND.icv.drc/run_details/duse_master.tmp /DCNFS/users/student/yli1/ELEN153/lab4/synopsys_custom/pvjob_lab4.NAND.icv.drc/run_details/duse_master
