CC	= g++

all:	stat bag

stat:	stat_main.cpp statistician2.cpp statistician2.h
	$(CC) -o statistician stat_main.cpp statistician2.cpp

bag: 	bag_main.cpp bag1.cxx bag1.h
	$(CC) -o bag bag_main.cpp bag1.cxx

clean:;	rm -f statistician bag
