CXX		= g++ -std=c++11
CXXFLAGS	= -g -Wall
OBJS		= Register.o Scope.o Symbol.o Tree.o Type.o Label.o\
		  allocator.o checker.o generator.o lexer.o parser.o writer.o
PROG		= scc

all:		$(PROG)

$(PROG):	$(OBJS)
		$(CXX) -o $(PROG) $(OBJS)

clean:;		$(RM) $(PROG) core *.o
